package rules;
//导入自定义的实体类
import com.cloud.domain.Message;
//规则名
rule "Hello World"  //条件语句
    when
    //当该实体的status属性为HELLO的时候，将该实体赋值给m，实体的message属性赋值给printMsg
        m : Message(status == Message.HELLO,printMsg : message)
    then

        System.out.println("11111111111111111111111111");
        System.out.println(printMsg);
        m.setMessage("GOODBYTE");
        m.setStatus(Message.GOODBYE);
         //更新实体，会重新触发规则
        update(m);
        System.out.println("222222222222222222");
     end